FactoryBot.define do
  ### Factories create a template for generating test data by acting as a blueprint for objects

  # The examples below were generated by copilot 
  ### (I believe Prof H hinted it would be a bad idea to include my personal information in fields 
  ### like in the commented out lines, so I enlisted Copilot to help lmao)

  # factory :address do
  #   association :customer
  #   is_billing {true}
  #   recipient {"man"}
  #   street_1 {"262 Avenue"}
  #   street_2 {"Room 8920"}
  #   city {"Pittsburgh"}
  #   state {"PA"}
  #   zip {"15213"}
  #   active {true}
  # end

  # factory :customers do
  #   first_name {"Tom"}
  #   last_name {"Bryant"}
  #   email {"tg****@cmu.edu"}
  #   phone {"6667897878"}
  #   active {true}
  # end

  ### I commented out the traits (which copilot made) bc I have no idea what they do

  # factory :customer do
  #   first_name { "John" }
  #   last_name { "Doe" }
  #   email { "john.doe@example.com" }
  #   phone { 1234567890 }
  #   active { true }

  #   # trait :inactive do
  #   #   active { false }
  #   # end
  # end

  # factory :address do
  #   association :customer
  #   recipient { "John Doe" }
  #   street_1 { "123 Main St" }
  #   city { "Pittsburgh" }
  #   state { "PA" }
  #   zip { "15213" }
  #   is_billing { false }
  #   active { true }

  #   # trait :billing do
  #   #   is_billing { true }
  #   # end

  #   # trait :inactive do
  #   #   active { false }
  #   # end
  # end

  # factory :order do
  #   association :customer
  #   association :address
  #   date { Date.today }
  #   grand_total { 100.00 }
  #   payment_receipt { "ABC123XYZ" }

  #   # trait :unpaid do
  #   #   payment_receipt { nil }
  #   # end
  # end

end