FactoryBot.define do
  factory :address do
    association :customer
    is_billing { false }
    recipient { "Ted Gershon" }
    street_1 { "123 Main St" }
    street_2 { nil }
    city { "Pittsburgh" }
    state { "PA" }
    zip { "15213" }
    active { true }
  end
end

### Code below was generated by something I typed in CLI --- I don't recall exactly what.
### It doesn't work...

### This is why you gotta be wary of who you trust.
### It be the ones you least expect sometimes.
### But those hurt the worst.
### It seems CLI was tight with the nil:NilClass errors more than me.
### Tough.

# FactoryBot.define do
#   factory :address do
#     customer { nil }
#     is_billing { false }
#     recipient { "MyString" }
#     street_1 { "MyString" }
#     street_2 { "MyString" }
#     city { "MyString" }
#     state { "MyString" }
#     zip { "MyString" }
#     active { false }
#   end
# end
