FactoryBot.define do
  factory :customer do
    first_name {"Ted"}
    last_name {"Gershon"}
    email {"tgershon@cmu.edu"}
    phone {"6667897878"}
    active {true}
  end
end

### Code below was generated by something I typed in CLI --- I don't recall exactly what
### Both the code above and below work

# FactoryBot.define do
#   factory :customer do
#     first_name { "MyString" }
#     last_name { "MyString" }
#     email { "MyString" }
#     phone { "MyString" }
#     active { false }
#   end
# end