FactoryBot.define do
  factory :order do
    association :customer
    association :address
    date { Date.today }
    grand_total { 100.00 }
    payment_receipt { "ABC123XYZ" }
  end
end

### Code below was generated by something I typed in CLI --- I don't recall exactly what
### It doesn't work though (sad)

# FactoryBot.define do
#   factory :order do
#     customer { nil }
#     address { nil }
#     date { "2025-02-02" }
#     grand_total { 1.5 }
#     payment_receipt { "MyString" }
#   end
# end
